language: node_js

node_js:
  - 10

before_script:
  - npm i
  - npm i -g ganache-cli

script:
  - ganache-cli -m 'deal copy supply rally height clutch tornado cabbage ill shoe pizza help' > /dev/null &
  - sleep 5
  - npm run test
