version: "3"

services:
  tx-payer-service:
    build: .
    volumes:
      - .:/usr/app
    ports:
      - 8010:8010
    links:
      - ganache
    environment:
      - NETWORK_URL=${NETWORK_URL}
      - WALLET_MNEOMONIC=${WALLET_MNEMONIC}
    command: npm start
  ganache:
    image: "daostack/migration:0.0.1-rc.30-v0"
    ports:
      - "8545:8545"
